services:
  - type: web
    name: ca-nursing-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir tools webapp:app --bind 0.0.0.0:$PORT
    plan: free
